version: "3.9"
services:
    gateway:
        env_file:
        - parameters.env
        container_name: gateway-server
        build: gateway
        ports:
        - "9080:8080"
        networks:
        - ftv-demo-network
        environment:
        - JAVA_TOOL_OPTIONS=-javaagent:./sl-cd-agent.jar -Dsl.tokenFile=./sltoken.txt -Dsl.appName=Calculator-Medhat/Jenkins-gateway -Dsl.buildName=0.0.1 -Dsl.labId=integ_dev_52ce_CalculatorMedhatjenkins -Dsl.includes=*i0.sealights.* -Dsl.workspace=/opt/app -Dsl.log.toConsole=true -Dsl.log.level=info
        volumes:
        - /var/lib/jenkins/workspace/calculator-medhat/sl-cd-agent.jar:.
        - /var/lib/jenkins/workspace/calculator-medhat/sltoken.txt:.
    calculator:
        env_file:
        - parameters.env
        container_name: calculator-server
        build: calculator
        ports:
        - "9081:8080"
        networks:
        - ftv-demo-network
        environment:
        - JAVA_TOOL_OPTIONS=-javaagent:./sl-cd-agent.jar -Dsl.tokenFile=./sltoken.txt -Dsl.appName=Calculator-Medhat/Jenkins-calculator -Dsl.buildName=0.0.1 -Dsl.labId=integ_dev_52ce_CalculatorMedhatjenkins -Dsl.includes=*i0.sealights.* -Dsl.workspace=/opt/app -Dsl.log.toConsole=true -Dsl.log.level=info
        volumes:
        - /var/lib/jenkins/workspace/calculator-medhat/sl-cd-agent.jar:.
        - /var/lib/jenkins/workspace/calculator-medhat/sltoken.txt:.

        
    summator:
        env_file:
        - parameters.env
        container_name: summator-server
        build: summator
        ports:
        - "9082:8080"
        networks:
        - ftv-demo-network
        environment:
        - JAVA_TOOL_OPTIONS=-javaagent:./sl-cd-agent.jar -Dsl.tokenFile=./sltoken.txt -Dsl.appName=Calculator-Medhat/Jenkins-summator -Dsl.buildName=0.0.1 -Dsl.labId=integ_dev_52ce_CalculatorMedhatjenkins -Dsl.includes=*i0.sealights.* -Dsl.workspace=/opt/app -Dsl.log.toConsole=true -Dsl.log.level=info
        volumes:
        - /var/lib/jenkins/workspace/calculator-medhat/sl-cd-agent.jar:.
        - /var/lib/jenkins/workspace/calculator-medhat/sltoken.txt:.
networks:
    ftv-demo-network:
        driver: bridge